site_name: Actuarial Exam Notes
site_url: https://example.com/
theme: material

nav:
  - Introductory:
    - Overview: Placeholder.md
    - ASA-P: Placeholder.md
    - ASA-FM: Placeholder.md
    - ASA-IFM: Placeholder.md
  - Actuarial Mathematics:
    - Overview: Placeholder.md
    - ASA-FAMS:
      - Review of Probability Theory: 3. Predictive Analytics/ASA-SRM/1. Review of Statistical Theory.md
    - ASA-FAML:
      - Review of Interest Theory: 3. Predictive Analytics/ASA-SRM/1. Review of Statistical Theory.md
      - Survival Models: 2. Actuarial Mathematics\ASA-FAML\1. Survival Models.md
    - ASA-ALTAM: Placeholder.md
  - Predictive Analytics:
    - Overview: 3. Predictive Analytics/Exam Overview.md
    - ASA-SRM:
      - Review of Statistical Theory: 3. Predictive Analytics/ASA-SRM/1. Review of Statistical Theory.md
      - Regression Overview: 3. Predictive Analytics/ASA-SRM/2. Regression Overview.md
      - Simple Linear Regression: 3. Predictive Analytics/ASA-SRM/3. Simple Linear Regression.md
    - ASA-PA: Placeholder.md

markdown_extensions:
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js