site_name: Actuarial Exam Notes
site_url: https://example.com/
theme: material

nav:
  - Introductory:
    - ASA-P: Placeholder.md
    - ASA-FM: Placeholder.md
    - ASA-IFM: Placeholder.md
  - Actuarial Mathematics:
    - Overview of Insurance: 2. Actuarial Mathematics\Overview of Insurance.md
    - ASA-FAMS:
      - Review of Probability Theory: 2. Actuarial Mathematics\ASA-FAMS\1. Review of Probability Theory.md
      - Frequency Models: 2. Actuarial Mathematics\ASA-FAMS\2. Frequency Models.md
      - Severity Models: 2. Actuarial Mathematics\ASA-FAMS\3. Severity Models.md
      - Aggregate Models: 2. Actuarial Mathematics\ASA-FAMS\4. Aggregate Models.md
      - Credibility: Placeholder.md
      - Ratemaking: Placeholder.md
      - Loss Reserving: Placeholder.md
    - ASA-FAML:
      - Survival Models: 2. Actuarial Mathematics\ASA-FAML\1. Survival Models.md
      - Life Tables: 2. Actuarial Mathematics\ASA-FAML\2. Life Tables.md
      - Life Assurances: 2. Actuarial Mathematics\ASA-FAML\3. Life Assurances.md
      - Life Annuities: 2. Actuarial Mathematics\ASA-FAML\4. Life Annuities.md
      - Variable Benefits: 2. Actuarial Mathematics\ASA-FAML\5. Variable Benefits.md
      - Premiums: 2. Actuarial Mathematics\ASA-FAML\6. Premiums.md
      - Reserves: 2. Actuarial Mathematics\ASA-FAML\7. Reserves.md
      - Model Estimation: 2. Actuarial Mathematics\ASA-FAML\8. Model Estimation.md
    - ASA-ALTAM:
      - Profit Testing: 2. Actuarial Mathematics\ASA-ALTAM\Profit Testing.md
      - Special: 2. Actuarial Mathematics\ASA-ALTAM\Special Products.md
  - Predictive Analytics: 
    - ASA-SRM:
      - Review of Statistical Theory: 3. Predictive Analytics/ASA-SRM/3. Review of Statistical Theory.md
      - Regression Overview: 3. Predictive Analytics/ASA-SRM/1. Regression Overview.md
      - Simple Linear Regression: 3. Predictive Analytics/ASA-SRM/2. Simple Linear Regression.md
      - Multiple Linear Regression: 3. Predictive Analytics/ASA-SRM/3. Multiple Linear Regression.md
      - Gauss Markov Theorem: 3. Predictive Analytics/ASA-SRM/4. Gauss Markov Theorem.md
      - Statistical Learning: 3. Predictive Analytics/ASA-SRM/5. Statistical Learning.md
    - ASA-PA: Placeholder.md
  - ILA Track:
    - FSA-LPM: Placeholder.md
    - FSA-LFM: Placeholder.md
    - FSA-ALM: Placeholder.md

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - config/extra.css

extra_javascript:
  - config/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js