site_name: Actuarial Exam Notes
site_url: https://example.com/
theme: material

nav:
  - Foundational:
    - Review of Linear Algebra: 0. Foundational/1. Review of Linear Algebra.md
    - Review of Calculus: 0. Foundational/2. Review of Calculus.md
    - Review of Statistical Theory: 0. Foundational/3. Review of Statistical Theory.md
  - Introductory:
    - Overview: Placeholder.md
    - ASA-P: Placeholder.md
    - ASA-FM: Placeholder.md
    - ASA-IFM: Placeholder.md
  - Actuarial Mathematics:
    - Overview: Placeholder.md
    - ASA-FAMS: Placeholder.md
    - ASA-FAML:
      - Survival Models: 2. Actuarial Mathematics\ASA-FAML\1. Survival Models.md
    - ASA-ALTAM: Placeholder.md
  - Predictive Analytics:
    - Overview: 3. Predictive Analytics/Exam Overview.md
    - ASA-SRM:
      - Regression Overview: 3. Predictive Analytics/ASA-SRM/1. Regression Overview.md
      - Simple Linear Regression: 3. Predictive Analytics/ASA-SRM/2. Simple Linear Regression.md
      - Multiple Linear Regression: 3. Predictive Analytics/ASA-SRM/3. Multiple Linear Regression.md
      - Gauss Markov Theorem: 3. Predictive Analytics/ASA-SRM/4. Gauss Markov Theorem.md
      - Statistical Learning: 3. Predictive Analytics/ASA-SRM/5. Statistical Learning.md
    - ASA-PA: Placeholder.md

markdown_extensions:
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js