site_name: Jerram's Actuarial Exam Notes
site_url: https://example.com/
theme: material

nav:
  - Introductory:
    - Overview: Placeholder.md
    - ASA-P: Placeholder.md
    - ASA-FM: Placeholder.md
    - ASA-IFM: Placeholder.md
  - Actuarial Mathematics:
    - Overview: Placeholder.md
    - ASA-FAMS: Placeholder.md
    - ASA-FAML: Placeholder.md
    - ASA-ALTAM: Placeholder.md
  - Predictive Analytics:
    - Overview: Predictive Analytics/Overview.md
    - ASA-SRM: Placeholder.md
    - ASA-PA: Placeholder.md


markdown_extensions:
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js